[build]
  publish = "dist"
  command = "npm run build:netlify"

[dev]
  command = "npm run dev:vite"
  targetPort = 5173
  port = 8888
  publish = "dist"
  framework = "#custom"
  autoLaunch = false

[build.environment]
  NODE_VERSION = "18"
  # Variáveis de ambiente para desenvolvimento local
  SUPABASE_URL = "https://qcqkfipckcnydsjjdral.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjcWtmaXBja2NueWRzampkcmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Mjc3MzcsImV4cCI6MjA3MTIwMzczN30.5Bq-1-TyOugW1-NrkDj_37lCYDvKJNiaRC6vFoWqXZk"
  VITE_SUPABASE_URL = "https://qcqkfipckcnydsjjdral.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjcWtmaXBja2NueWRzampkcmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Mjc3MzcsImV4cCI6MjA3MTIwMzczN30.5Bq-1-TyOugW1-NrkDj_37lCYDvKJNiaRC6vFoWqXZk"
  NEXT_PUBLIC_SUPABASE_URL = "https://qcqkfipckcnydsjjdral.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjcWtmaXBja2NueWRzampkcmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2Mjc3MzcsImV4cCI6MjA3MTIwMzczN30.5Bq-1-TyOugW1-NrkDj_37lCYDvKJNiaRC6vFoWqXZk"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Exclude static assets from SPA redirect
[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200

[[redirects]]
  from = "/*.json"
  to = "/:splat.json"
  status = 200

# Exclude source files from SPA redirect
[[redirects]]
  from = "/src/*"
  to = "/:splat"
  status = 200

# Exclude Vite virtual modules from SPA redirect
[[redirects]]
  from = "/@*"
  to = "/:splat"
  status = 200

# Exclude node_modules from SPA redirect
[[redirects]]
  from = "/node_modules/*"
  to = "/:splat"
  status = 200

# Exclude Vite client and HMR from SPA redirect
[[redirects]]
  from = "/client"
  to = "/client"
  status = 200

# SPA fallback for all other routes (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions-build"
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"