[build]
  publish = "dist"
  command = "npm run build:netlify"

[dev]
  port = 8888
  autoLaunch = false
  framework = "#static"
  publish = "dist"
  functionsPort = 8888
  # Priorizar carregamento das funções
  functions = "netlify/functions-build"
  # Configurações para otimizar o carregamento das funções
  [dev.env]
    NETLIFY_DEV = "true"
    NODE_ENV = "development"



[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  
  # Excluir arquivos estáticos e de desenvolvimento do redirecionamento
  [[redirects.exceptions]]
    from = "/*.js"
  [[redirects.exceptions]]
    from = "/*.css"
  [[redirects.exceptions]]
    from = "/*.png"
  [[redirects.exceptions]]
    from = "/*.jpg"
  [[redirects.exceptions]]
    from = "/*.jpeg"
  [[redirects.exceptions]]
    from = "/*.gif"
  [[redirects.exceptions]]
    from = "/*.svg"
  [[redirects.exceptions]]
    from = "/*.ico"
  [[redirects.exceptions]]
    from = "/*.woff"
  [[redirects.exceptions]]
    from = "/*.woff2"
  [[redirects.exceptions]]
    from = "/*.ttf"
  [[redirects.exceptions]]
    from = "/*.eot"
  [[redirects.exceptions]]
    from = "/*.json"
  [[redirects.exceptions]]
    from = "/*.xml"
  [[redirects.exceptions]]
    from = "/*.txt"
  [[redirects.exceptions]]
    from = "/*.md"
  [[redirects.exceptions]]
    from = "/*.pdf"
  [[redirects.exceptions]]
    from = "/*.zip"
  [[redirects.exceptions]]
    from = "/*.tar.gz"
  [[redirects.exceptions]]
    from = "/*.map"
  [[redirects.exceptions]]
    from = "/src/*"
  [[redirects.exceptions]]
    from = "/@vite/*"
  [[redirects.exceptions]]
    from = "/@fs/*"
  [[redirects.exceptions]]
    from = "/node_modules/*"
  [[redirects.exceptions]]
    from = "/__vite_ping"
  [[redirects.exceptions]]
    from = "/vite.svg"

[functions]
  directory = "netlify/functions-build"
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"