[build]
  publish = "dist"
  command = "npm run build:netlify"

[build.environment]
  NODE_VERSION = "18"
  # Variáveis de ambiente necessárias (configurar no dashboard do Netlify)
  # SUPABASE_URL = "https://qcqkfipckcnydsjjdral.supabase.co"
  # SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
  # VITE_SUPABASE_URL = "https://qcqkfipckcnydsjjdral.supabase.co"
  # VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
  # NEXT_PUBLIC_SUPABASE_URL = "https://qcqkfipckcnydsjjdral.supabase.co"
  # NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions-build"
  node_bundler = "nft"
  external_node_modules = ["@supabase/supabase-js", "hono", "@hono/zod-validator", "zod"]
  included_files = ["dist/worker/**", "src/shared/**"]

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"