[build]
  publish = "dist"
  command = "npm run build:netlify"

[dev]
  command = "npm run dev:vite"
  targetPort = 5173
  port = 8888
  publish = "dist"
  framework = "#custom"
  autoLaunch = false



[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Exclude static assets from SPA redirect
[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200

[[redirects]]
  from = "/*.json"
  to = "/:splat.json"
  status = 200

# Exclude source files from SPA redirect
[[redirects]]
  from = "/src/*"
  to = "/:splat"
  status = 200

# Exclude Vite virtual modules from SPA redirect
[[redirects]]
  from = "/@*"
  to = "/:splat"
  status = 200

# Exclude node_modules from SPA redirect
[[redirects]]
  from = "/node_modules/*"
  to = "/:splat"
  status = 200

# Exclude Vite client and HMR from SPA redirect
[[redirects]]
  from = "/client"
  to = "/client"
  status = 200

# SPA fallback for all other routes (must be last)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions-build"
  node_bundler = "esbuild"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"