"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.CardContent = exports.CardDescription = exports.CardTitle = exports.CardFooter = exports.CardHeader = exports.Card = void 0;
const react_1 = __importDefault(require("react"));
const utils_1 = require("@/react-app/lib/utils");
const Card = react_1.default.forwardRef(({ className, ...props }, ref) => (<div ref={ref} className={(0, utils_1.cn)('rounded-lg border bg-card text-card-foreground shadow-sm', className)} {...props}/>));
exports.Card = Card;
Card.displayName = 'Card';
const CardHeader = react_1.default.forwardRef(({ className, ...props }, ref) => (<div ref={ref} className={(0, utils_1.cn)('flex flex-col space-y-1.5 p-6', className)} {...props}/>));
exports.CardHeader = CardHeader;
CardHeader.displayName = 'CardHeader';
const CardTitle = react_1.default.forwardRef(({ className, ...props }, ref) => (<h3 ref={ref} className={(0, utils_1.cn)('text-2xl font-semibold leading-none tracking-tight', className)} {...props}/>));
exports.CardTitle = CardTitle;
CardTitle.displayName = 'CardTitle';
const CardDescription = react_1.default.forwardRef(({ className, ...props }, ref) => (<p ref={ref} className={(0, utils_1.cn)('text-sm text-muted-foreground', className)} {...props}/>));
exports.CardDescription = CardDescription;
CardDescription.displayName = 'CardDescription';
const CardContent = react_1.default.forwardRef(({ className, ...props }, ref) => (<div ref={ref} className={(0, utils_1.cn)('p-6 pt-0', className)} {...props}/>));
exports.CardContent = CardContent;
CardContent.displayName = 'CardContent';
const CardFooter = react_1.default.forwardRef(({ className, ...props }, ref) => (<div ref={ref} className={(0, utils_1.cn)('flex items-center p-6 pt-0', className)} {...props}/>));
exports.CardFooter = CardFooter;
CardFooter.displayName = 'CardFooter';
