
INSERT OR REPLACE INTO kpis (nome_kpi, valor_meta_kpi, peso_kpi, turno_kpi, funcao_kpi, created_at, updated_at) VALUES
  ('Produtividade na Separação', 99.5, 10.00, 'Manhã', 'Ajudante de Armazém', datetime('now'), datetime('now')),
  ('Produtividade na Separação', 99.5, 10.00, 'Tarde', 'Ajudante de Armazém', datetime('now'), datetime('now')),
  ('Produtividade na Separação', 99.5, 10.00, 'Noite', 'Ajudante de Armazém', datetime('now'), datetime('now')),
  ('Acuracidade na Separação', 99.8, 15.00, 'Manhã', 'Ajudante de Armazém', datetime('now'), datetime('now')),
  ('Acuracidade na Separação', 99.8, 15.00, 'Tarde', 'Ajudante de Armazém', datetime('now'), datetime('now')),
  ('Acuracidade na Separação', 99.8, 15.00, 'Noite', 'Ajudante de Armazém', datetime('now'), datetime('now')),
  ('Disponibilidade de Equipment', 98.0, 12.00, 'Geral', 'Operador de Empilhadeira', datetime('now'), datetime('now')),
  ('Eficiência Operacional', 95.0, 18.00, 'Manhã', 'Operador de Empilhadeira', datetime('now'), datetime('now')),
  ('Eficiência Operacional', 95.0, 18.00, 'Tarde', 'Operador de Empilhadeira', datetime('now'), datetime('now')),
  ('Eficiência Operacional', 95.0, 18.00, 'Noite', 'Operador de Empilhadeira', datetime('now'), datetime('now')),
  ('Acuracidade na Conferência', 99.9, 20.00, 'Manhã', 'Conferente', datetime('now'), datetime('now')),
  ('Acuracidade na Conferência', 99.9, 20.00, 'Tarde', 'Conferente', datetime('now'), datetime('now')),
  ('Acuracidade na Conferência', 99.9, 20.00, 'Noite', 'Conferente', datetime('now'), datetime('now')),
  ('Velocidade na Conferência', 95.0, 12.00, 'Manhã', 'Conferente', datetime('now'), datetime('now')),
  ('Velocidade na Conferência', 95.0, 12.00, 'Tarde', 'Conferente', datetime('now'), datetime('now')),
  ('Velocidade na Conferência', 95.0, 12.00, 'Noite', 'Conferente', datetime('now'), datetime('now')),
  ('Gestão de Equipe', 98.0, 25.00, 'Geral', 'Supervisor', datetime('now'), datetime('now')),
  ('Cumprimento de Metas', 95.0, 20.00, 'Geral', 'Supervisor', datetime('now'), datetime('now')),
  ('Indicadores Gerais', 97.0, 30.00, 'Geral', 'Gerente', datetime('now'), datetime('now')),
  ('Gestão de Processos', 96.0, 25.00, 'Geral', 'Gerente', datetime('now'), datetime('now')),
  ('Segurança e Qualidade', 99.0, 22.00, 'Geral', 'Ajudante de Armazém', datetime('now'), datetime('now')),
  ('Segurança e Qualidade', 99.0, 22.00, 'Geral', 'Operador de Empilhadeira', datetime('now'), datetime('now')),
  ('Segurança e Qualidade', 99.0, 22.00, 'Geral', 'Conferente', datetime('now'), datetime('now')),
  ('Melhoria Contínua', 90.0, 15.00, 'Geral', 'Supervisor', datetime('now'), datetime('now'));
